FROM node:22-alpine

WORKDIR /app

COPY gateway/package*.json ./gateway/

RUN cd gateway && npm install

COPY gateway ./gateway
COPY proto ./proto

WORKDIR /app/gateway

RUN npx tsc

EXPOSE 4000

CMD ["node", "dist/index.js"]