FROM node:22-alpine

WORKDIR /app

COPY order-service/package*.json ./order-service/

RUN cd order-service && npm install

COPY order-service ./order-service
COPY proto ./proto

WORKDIR /app/order-service

RUN npx tsc

EXPOSE 50052

CMD ["node", "dist/index.js"]