FROM node:22-alpine

WORKDIR /app

COPY inventory-service/package*.json ./inventory-service/

RUN cd inventory-service && npm install

COPY inventory-service ./inventory-service
COPY proto ./proto

WORKDIR /app/inventory-service

RUN npx tsc

EXPOSE 50051

CMD ["node", "dist/index.js"]